### NumPy
- It's fast as compared to python
- Optimizations written in C
- Vectorization via broadcasting (avoiding loops)
- Central Object - Numpy Array
- It's a library for Linear Algebra and a bit of probability
- Scalor -
  ```python
      24, 25
  ```
- Vector - rows or column
  ```python
    [ 2 4 6 ] 
      #or
      [ 1
        3
        5 ]
   ```
 - Matrix - rows * column
   ```python
       [ 1 2 3
         4 5 6
         7 8 9 ]
   ```

In [1]:
import numpy as np

### Array Vs List
- List look like an array but it's works more like a generic data structure
- But Numpy array can be used to perform arthmetic operation

In [9]:
L = [1,2,3]
[print(x) for x in L]

1
2
3


[None, None, None]

In [11]:
L*2 #or L+2 print list twice

[1, 2, 3, 1, 2, 3]

In [10]:
A = np.array([1,2,3])
for x in A:
    print(x)

1
2
3


In [12]:
# whereas in array it perform arthmetic operation
A+2

array([3, 4, 5])

In [13]:
A*[5]

array([ 5, 10, 15])

In [14]:
A + np.array([5,10,15])

array([ 6, 12, 18])

In [16]:
a = np.array([1,2])
b = np.array([3,4])
for e,f in zip(a,b):
    print(e*f)

3
8


### DataTypes / Attributes

In [93]:
# N Dimensional Array 
# 1 Dimensional/Vector - shape (1,3) ~ row,col 
arr_1_dim = np.array([1,2,3])
arr_1_dim

array([1, 2, 3])

In [94]:
arr_1_dim.shape

(3,)

In [95]:
# N Dimensional/Matrix - shape (2,3) ~ row,col 
arr_n_dim_1 = np.array([[1.1,2,3.6],
                    [4,5.8,6]])
arr_n_dim_1

array([[1.1, 2. , 3.6],
       [4. , 5.8, 6. ]])

In [96]:
arr_n_dim_1.shape # 2 rows, 3 column in each row, 0 dimesion as 1 array

(2, 3)

In [97]:
# N Dimensional/Matrix - shape (3,3,3) ~ row,col,dimesion 
arr_n_dim_2 = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,19]]])
arr_n_dim_2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 19]]])

In [98]:
arr_n_dim_2.shape # 3 rows, 2 column in each row, 3 dimesion for 3 arrays

(3, 2, 3)

In [99]:
# to get dimesion use ndim
f'arr_1_dim has {arr_1_dim.ndim} dimesion, arr_n_dim_1 has {arr_n_dim_1.ndim} dimesion, arr_n_dim_2 has {arr_n_dim_2.ndim} dimesion'

'arr_1_dim has 1 dimesion, arr_n_dim_1 has 2 dimesion, arr_n_dim_2 has 3 dimesion'

In [100]:
# to get datatype use dtype
f'arr_1_dim has {arr_1_dim.dtype} datatype, arr_n_dim_1 has {arr_n_dim_1.dtype} datatype, arr_n_dim_2 has {arr_n_dim_2.dtype} datatype'

'arr_1_dim has int64 datatype, arr_n_dim_1 has float64 datatype, arr_n_dim_2 has int64 datatype'

In [101]:
# to get no of elements in np array use size
f'arr_1_dim has {arr_1_dim.size} elements, arr_n_dim_1 has {arr_n_dim_1.size} elements, arr_n_dim_2 has {arr_n_dim_2.size} elements'

'arr_1_dim has 3 elements, arr_n_dim_1 has 6 elements, arr_n_dim_2 has 18 elements'

In [102]:
type(arr_1dim), type(arr_n_dim_1), type(arr_n_dim_2)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a Df from NumPy array

In [103]:
import pandas as pd
df = pd.DataFrame(arr_n_dim_1)
df

0    1    2
0  1.1  2.0  3.6
1  4.0  5.8  6.0

### Flattening an array means converting a multi-dimensional array into a lower-dimensional array. 
- In the context of converting a 3D numpy array to a 2D array, flattening involves collapsing the dimensions so that each sub-array becomes a row in the new 2D array

In [104]:
# Original 3D array
arr_n_dim_2 = np.array([[[1, 2, 3], [4, 5, 6]],
                        [[7, 8, 9], [10, 11, 12]],
                        [[13, 14, 15], [16, 17, 19]]])
# This array has the shape (3, 2, 3), meaning it has 3 blocks, each containing 2 rows, and each row has 3 elements.
# Flattening Process - reshape method to change the shape of the array. 
flattened_array = arr_n_dim_2.reshape(-1, arr_n_dim_2.shape[-1])
# -1 tells numpy to automatically calculate the appropriate size for that dimension based on the original array’s size
# arr_n_dim_2.shape[-1] gives the size of the last dimension, which is 3 in this case.

In [105]:
flattened_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 19]])

In [106]:
df = pd.DataFrame(flattened_array, columns=['A', 'B', 'C'])
df

A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  19

### Creating Arrays
- Type Shift + Tab inside ()

In [107]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
range_array = np.arange(0,100,5)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [125]:
random_array = np.random.randint(low=0, high=100, size=(3,4,5)) # np.random.randint(0, 100, (3,4,5))
random_array

array([[[50, 36, 34, 48, 93],
        [ 3, 98, 42, 77, 21],
        [73,  0, 10, 43, 58],
        [23, 59,  2, 98, 62]],

       [[35, 94, 67, 82, 46],
        [99, 20, 81, 50, 27],
        [14, 41, 58, 65, 36],
        [10, 86, 43, 11,  2]],

       [[51, 80, 32, 54,  0],
        [38, 19, 46, 42, 56],
        [60, 77, 30, 24,  2],
        [ 3, 94, 98, 13, 40]]])

In [116]:
random_array_1 = np.random.random(size=(5,3))
random_array_1

array([[0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  ]])

In [118]:
random_array_1.shape

(5, 3)

### Random Seed in NumPy
- Is like a starting point for generating random numbers.
- When you set a random seed using numpy.random.seed(), it ensures that you get the same sequence of random numbers every time you run your code.
- This is useful for debugging and testing because it makes your results reproducible
- Think of it like setting a specific starting point in a shuffled deck of cards. If you start from the same point every time, you’ll always get the same order of cards, even though they appear random.
- The difference between numpy.random.seed(7) and numpy.random.seed(999) is the starting point for generating random numbers. Each seed value initializes the random number generator in a different way, leading to different sequences of random numbers.
- The key point is that using the same seed value will always produce the same sequence of random numbers, which is useful for reproducibility. Different seed values will produce different sequences.

In [120]:
# make sure that random generate same set of numbers 
np.random.seed(seed=0)
nonrandom_array = np.random.random(size=(5,3))
nonrandom_array

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

### Viewing Array Or Matrix

In [126]:
random_array

array([[[50, 36, 34, 48, 93],
        [ 3, 98, 42, 77, 21],
        [73,  0, 10, 43, 58],
        [23, 59,  2, 98, 62]],

       [[35, 94, 67, 82, 46],
        [99, 20, 81, 50, 27],
        [14, 41, 58, 65, 36],
        [10, 86, 43, 11,  2]],

       [[51, 80, 32, 54,  0],
        [38, 19, 46, 42, 56],
        [60, 77, 30, 24,  2],
        [ 3, 94, 98, 13, 40]]])

In [127]:
random_array[0]

array([[50, 36, 34, 48, 93],
       [ 3, 98, 42, 77, 21],
       [73,  0, 10, 43, 58],
       [23, 59,  2, 98, 62]])

In [128]:
random_array[:2, :2, :2]

array([[[50, 36],
        [ 3, 98]],

       [[35, 94],
        [99, 20]]])

#### Create a 4-dimensional array with the shape 2x3x4x5, filled with random integers from 0 to 9.
- In plain English, it means you’re creating a “box” of numbers that has:
    - 2 “big boxes”
    - Each “big box” contains 3 “medium boxes”
    - Each “medium box” contains 4 “small boxes”
    - Each “small box” contains 5 random numbers between 0 and 9

In [129]:
random_array_4_dim = np.random.randint(10, size=(2,3,4,5))
random_array_4_dim

array([[[[8, 3, 8, 2, 8],
         [4, 3, 0, 4, 3],
         [6, 9, 8, 0, 8],
         [5, 9, 0, 9, 6]],

        [[5, 3, 1, 8, 0],
         [4, 9, 6, 5, 7],
         [8, 8, 9, 2, 8],
         [6, 6, 9, 1, 6]],

        [[8, 8, 3, 2, 3],
         [6, 3, 6, 5, 7],
         [0, 8, 4, 6, 5],
         [8, 2, 3, 9, 7]]],


       [[[5, 3, 4, 5, 3],
         [3, 7, 9, 9, 9],
         [7, 3, 2, 3, 9],
         [7, 7, 5, 1, 2]],

        [[2, 8, 1, 5, 8],
         [4, 0, 2, 5, 5],
         [0, 8, 1, 1, 0],
         [3, 8, 8, 4, 4]],

        [[0, 9, 3, 7, 3],
         [2, 1, 1, 2, 1],
         [4, 2, 5, 5, 5],
         [2, 5, 7, 7, 6]]]])